backend:
  name: github
  repo: torn-flight-club/flight-club-wiki
  branch: main

media_folder: static/img
public_folder: /img

collections:
  - name: "docs_public"
    label: "Public Docs"
    folder: "docs-public"
    create: true
    slug: "{{slug}}"
    format: "frontmatter"
    extension: "md"
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "body", label: "Body", widget: "markdown" }

  - name: "docs_internal"
    label: "Internal Docs"
    folder: "docs-internal"
    create: true
    slug: "{{slug}}"
    format: "frontmatter"
    extension: "md"
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "body", label: "Body", widget: "markdown" }
